package telas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MASTER
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        backPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        nomeBackground = new javax.swing.JPanel();
        nomeTextField = new javax.swing.JTextField();
        dataField = new javax.swing.JLabel();
        nomeBackground1 = new javax.swing.JPanel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        dataField1 = new javax.swing.JLabel();
        nomeBackground6 = new javax.swing.JPanel();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        dataField2 = new javax.swing.JLabel();
        nomeBackground7 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        dataField3 = new javax.swing.JLabel();
        nomeBackground8 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        dataField5 = new javax.swing.JLabel();
        nomeBackground9 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        dataField6 = new javax.swing.JLabel();
        nomeBackground10 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        dataField7 = new javax.swing.JLabel();
        nomeBackground11 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        dataField8 = new javax.swing.JLabel();
        nomeBackground12 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        dataField9 = new javax.swing.JLabel();
        nomeBackground13 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        dataField10 = new javax.swing.JLabel();
        dataField11 = new javax.swing.JLabel();
        escolhaButton = new javax.swing.JRadioButton();
        escolhaButton1 = new javax.swing.JRadioButton();
        dataField12 = new javax.swing.JLabel();
        nomeBackground14 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        nomeBackground15 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        dataField13 = new javax.swing.JLabel();
        dataField14 = new javax.swing.JLabel();
        dataField15 = new javax.swing.JLabel();
        nomeBackground16 = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        nomeBackground17 = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        nomeBackground18 = new javax.swing.JPanel();
        jTextField11 = new javax.swing.JTextField();
        dataField16 = new javax.swing.JLabel();
        nomeBackground19 = new javax.swing.JPanel();
        jTextField12 = new javax.swing.JTextField();
        dataField17 = new javax.swing.JLabel();
        nomeBackground20 = new javax.swing.JPanel();
        jTextField13 = new javax.swing.JTextField();
        nomeBackground21 = new javax.swing.JPanel();
        jTextField14 = new javax.swing.JTextField();
        dataField18 = new javax.swing.JLabel();
        dataField19 = new javax.swing.JLabel();
        dataField20 = new javax.swing.JLabel();
        nomeBackground22 = new javax.swing.JPanel();
        jTextField15 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        backPanel.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\MASTER\\Desktop\\Escola\\TP1\\TrabalhoFinal_Sindicato\\logoResized2.png")); // NOI18N

        nomeBackground.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackgroundLayout = new javax.swing.GroupLayout(nomeBackground);
        nomeBackground.setLayout(nomeBackgroundLayout);
        nomeBackgroundLayout.setHorizontalGroup(
            nomeBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nomeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );
        nomeBackgroundLayout.setVerticalGroup(
            nomeBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField.setText("Nome");

        nomeBackground1.setBackground(new java.awt.Color(53, 0, 113));

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nomeBackground1Layout = new javax.swing.GroupLayout(nomeBackground1);
        nomeBackground1.setLayout(nomeBackground1Layout);
        nomeBackground1Layout.setHorizontalGroup(
            nomeBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        );
        nomeBackground1Layout.setVerticalGroup(
            nomeBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataField1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField1.setText("CPF");

        nomeBackground6.setBackground(new java.awt.Color(53, 0, 113));

        jFormattedTextField7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nomeBackground6Layout = new javax.swing.GroupLayout(nomeBackground6);
        nomeBackground6.setLayout(nomeBackground6Layout);
        nomeBackground6Layout.setHorizontalGroup(
            nomeBackground6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );
        nomeBackground6Layout.setVerticalGroup(
            nomeBackground6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jFormattedTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dataField2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField2.setText("RG");

        nomeBackground7.setBackground(new java.awt.Color(53, 0, 113));

        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolher", "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viúvo(a)", "Separado(a) Judicialmente" }));

        javax.swing.GroupLayout nomeBackground7Layout = new javax.swing.GroupLayout(nomeBackground7);
        nomeBackground7.setLayout(nomeBackground7Layout);
        nomeBackground7Layout.setHorizontalGroup(
            nomeBackground7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1, 0, 0, Short.MAX_VALUE)
        );
        nomeBackground7Layout.setVerticalGroup(
            nomeBackground7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dataField3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField3.setText("Estado Civil");

        nomeBackground8.setBackground(new java.awt.Color(53, 0, 113));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nomeBackground8Layout = new javax.swing.GroupLayout(nomeBackground8);
        nomeBackground8.setLayout(nomeBackground8Layout);
        nomeBackground8Layout.setHorizontalGroup(
            nomeBackground8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
        );
        nomeBackground8Layout.setVerticalGroup(
            nomeBackground8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dataField5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField5.setText("Naturalidade-Nacionalidade");

        nomeBackground9.setBackground(new java.awt.Color(53, 0, 113));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nomeBackground9Layout = new javax.swing.GroupLayout(nomeBackground9);
        nomeBackground9.setLayout(nomeBackground9Layout);
        nomeBackground9Layout.setHorizontalGroup(
            nomeBackground9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
        );
        nomeBackground9Layout.setVerticalGroup(
            nomeBackground9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataField6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField6.setText("Endereço");

        nomeBackground10.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackground10Layout = new javax.swing.GroupLayout(nomeBackground10);
        nomeBackground10.setLayout(nomeBackground10Layout);
        nomeBackground10Layout.setHorizontalGroup(
            nomeBackground10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
        );
        nomeBackground10Layout.setVerticalGroup(
            nomeBackground10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dataField7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField7.setText("Pai");

        nomeBackground11.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackground11Layout = new javax.swing.GroupLayout(nomeBackground11);
        nomeBackground11.setLayout(nomeBackground11Layout);
        nomeBackground11Layout.setHorizontalGroup(
            nomeBackground11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField4)
        );
        nomeBackground11Layout.setVerticalGroup(
            nomeBackground11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dataField8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField8.setText("Mãe");

        nomeBackground12.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackground12Layout = new javax.swing.GroupLayout(nomeBackground12);
        nomeBackground12.setLayout(nomeBackground12Layout);
        nomeBackground12Layout.setHorizontalGroup(
            nomeBackground12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        );
        nomeBackground12Layout.setVerticalGroup(
            nomeBackground12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dataField9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField9.setText("E-mail");

        nomeBackground13.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackground13Layout = new javax.swing.GroupLayout(nomeBackground13);
        nomeBackground13.setLayout(nomeBackground13Layout);
        nomeBackground13Layout.setHorizontalGroup(
            nomeBackground13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
        );
        nomeBackground13Layout.setVerticalGroup(
            nomeBackground13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dataField10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField10.setText("Grau de Escolaridade");

        dataField11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField11.setText("Telefone");

        escolhaButton.setBackground(new java.awt.Color(255, 255, 255));
        escolhaButton.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        escolhaButton.setText("Ensino Superior Completo");

        escolhaButton1.setBackground(new java.awt.Color(255, 255, 255));
        escolhaButton1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        escolhaButton1.setText("Ensino Superior Incompleto");

        dataField12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField12.setText("Curso");

        nomeBackground14.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackground14Layout = new javax.swing.GroupLayout(nomeBackground14);
        nomeBackground14.setLayout(nomeBackground14Layout);
        nomeBackground14Layout.setHorizontalGroup(
            nomeBackground14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
        );
        nomeBackground14Layout.setVerticalGroup(
            nomeBackground14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        nomeBackground15.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackground15Layout = new javax.swing.GroupLayout(nomeBackground15);
        nomeBackground15.setLayout(nomeBackground15Layout);
        nomeBackground15Layout.setHorizontalGroup(
            nomeBackground15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
        );
        nomeBackground15Layout.setVerticalGroup(
            nomeBackground15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground15Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dataField13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField13.setText("Especialização");

        dataField14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField14.setText("Número CRO");

        dataField15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField15.setText("Universidade");

        nomeBackground16.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackground16Layout = new javax.swing.GroupLayout(nomeBackground16);
        nomeBackground16.setLayout(nomeBackground16Layout);
        nomeBackground16Layout.setHorizontalGroup(
            nomeBackground16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
        );
        nomeBackground16Layout.setVerticalGroup(
            nomeBackground16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground16Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        nomeBackground17.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackground17Layout = new javax.swing.GroupLayout(nomeBackground17);
        nomeBackground17.setLayout(nomeBackground17Layout);
        nomeBackground17Layout.setHorizontalGroup(
            nomeBackground17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
        );
        nomeBackground17Layout.setVerticalGroup(
            nomeBackground17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground17Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        nomeBackground18.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackground18Layout = new javax.swing.GroupLayout(nomeBackground18);
        nomeBackground18.setLayout(nomeBackground18Layout);
        nomeBackground18Layout.setHorizontalGroup(
            nomeBackground18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField11)
        );
        nomeBackground18Layout.setVerticalGroup(
            nomeBackground18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground18Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dataField16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField16.setText("Ano de Formatura");

        nomeBackground19.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackground19Layout = new javax.swing.GroupLayout(nomeBackground19);
        nomeBackground19.setLayout(nomeBackground19Layout);
        nomeBackground19Layout.setHorizontalGroup(
            nomeBackground19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );
        nomeBackground19Layout.setVerticalGroup(
            nomeBackground19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground19Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dataField17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField17.setText("Previsão de Graduação");

        nomeBackground20.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackground20Layout = new javax.swing.GroupLayout(nomeBackground20);
        nomeBackground20.setLayout(nomeBackground20Layout);
        nomeBackground20Layout.setHorizontalGroup(
            nomeBackground20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField13)
        );
        nomeBackground20Layout.setVerticalGroup(
            nomeBackground20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground20Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        nomeBackground21.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackground21Layout = new javax.swing.GroupLayout(nomeBackground21);
        nomeBackground21.setLayout(nomeBackground21Layout);
        nomeBackground21Layout.setHorizontalGroup(
            nomeBackground21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField14, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );
        nomeBackground21Layout.setVerticalGroup(
            nomeBackground21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground21Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dataField18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField18.setText("Semestres Cursados");

        dataField19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField19.setText("Endereço do Consultório");

        dataField20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField20.setText("Celular");

        nomeBackground22.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackground22Layout = new javax.swing.GroupLayout(nomeBackground22);
        nomeBackground22.setLayout(nomeBackground22Layout);
        nomeBackground22Layout.setHorizontalGroup(
            nomeBackground22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField15, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        );
        nomeBackground22Layout.setVerticalGroup(
            nomeBackground22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground22Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout backPanelLayout = new javax.swing.GroupLayout(backPanel);
        backPanel.setLayout(backPanelLayout);
        backPanelLayout.setHorizontalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(backPanelLayout.createSequentialGroup()
                                    .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dataField14)
                                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(nomeBackground18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(dataField16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGap(45, 45, 45))
                                .addComponent(nomeBackground16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dataField19)
                            .addComponent(nomeBackground20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(530, 530, 530))
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataField13)
                            .addGroup(backPanelLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(logo)
                                .addGap(35, 35, 35)
                                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(dataField)
                                        .addComponent(nomeBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(backPanelLayout.createSequentialGroup()
                                            .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(nomeBackground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(dataField1))
                                            .addGap(18, 18, 18)
                                            .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(dataField9)
                                                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(backPanelLayout.createSequentialGroup()
                                                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(nomeBackground6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(dataField2))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(dataField3)
                                                            .addComponent(nomeBackground7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                    .addComponent(nomeBackground11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(backPanelLayout.createSequentialGroup()
                                                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(dataField6)
                                                            .addComponent(nomeBackground9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(dataField8))
                                                        .addGap(0, 0, Short.MAX_VALUE))))))
                                    .addGroup(backPanelLayout.createSequentialGroup()
                                        .addGap(191, 191, 191)
                                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dataField10)
                                            .addComponent(nomeBackground13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(escolhaButton)))))
                            .addComponent(dataField7)
                            .addComponent(dataField5)
                            .addGroup(backPanelLayout.createSequentialGroup()
                                .addComponent(nomeBackground14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dataField12)
                                    .addComponent(nomeBackground15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomeBackground17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dataField15)
                                    .addComponent(nomeBackground19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dataField17)
                                    .addComponent(nomeBackground21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dataField18))))
                        .addContainerGap())
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeBackground8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeBackground10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataField11)
                            .addComponent(dataField20)
                            .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nomeBackground12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nomeBackground22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(escolhaButton1)
                        .addGap(15, 15, 15))))
        );
        backPanelLayout.setVerticalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addComponent(dataField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataField1)
                            .addComponent(dataField2)
                            .addComponent(dataField3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nomeBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nomeBackground6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(nomeBackground7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(logo))
                .addGap(38, 38, 38)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataField5)
                    .addComponent(dataField6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomeBackground8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomeBackground9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataField7)
                    .addComponent(dataField8))
                .addGap(1, 1, 1)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomeBackground10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomeBackground11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataField9)
                    .addComponent(dataField11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nomeBackground12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeBackground13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataField20)
                    .addComponent(dataField10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeBackground22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(escolhaButton)
                        .addComponent(escolhaButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataField12)
                    .addComponent(dataField13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addComponent(nomeBackground14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataField14)
                            .addComponent(dataField15)))
                    .addComponent(nomeBackground15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeBackground17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeBackground16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataField16)
                    .addComponent(dataField17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomeBackground19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomeBackground18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataField18)
                    .addComponent(dataField19))
                .addGap(3, 3, 3)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backPanelLayout.createSequentialGroup()
                        .addComponent(nomeBackground21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addComponent(nomeBackground20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jScrollPane1.setViewportView(backPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jFormattedTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField7ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backPanel;
    private javax.swing.JLabel dataField;
    private javax.swing.JLabel dataField1;
    private javax.swing.JLabel dataField10;
    private javax.swing.JLabel dataField11;
    private javax.swing.JLabel dataField12;
    private javax.swing.JLabel dataField13;
    private javax.swing.JLabel dataField14;
    private javax.swing.JLabel dataField15;
    private javax.swing.JLabel dataField16;
    private javax.swing.JLabel dataField17;
    private javax.swing.JLabel dataField18;
    private javax.swing.JLabel dataField19;
    private javax.swing.JLabel dataField2;
    private javax.swing.JLabel dataField20;
    private javax.swing.JLabel dataField3;
    private javax.swing.JLabel dataField5;
    private javax.swing.JLabel dataField6;
    private javax.swing.JLabel dataField7;
    private javax.swing.JLabel dataField8;
    private javax.swing.JLabel dataField9;
    private javax.swing.JRadioButton escolhaButton;
    private javax.swing.JRadioButton escolhaButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel nomeBackground;
    private javax.swing.JPanel nomeBackground1;
    private javax.swing.JPanel nomeBackground10;
    private javax.swing.JPanel nomeBackground11;
    private javax.swing.JPanel nomeBackground12;
    private javax.swing.JPanel nomeBackground13;
    private javax.swing.JPanel nomeBackground14;
    private javax.swing.JPanel nomeBackground15;
    private javax.swing.JPanel nomeBackground16;
    private javax.swing.JPanel nomeBackground17;
    private javax.swing.JPanel nomeBackground18;
    private javax.swing.JPanel nomeBackground19;
    private javax.swing.JPanel nomeBackground20;
    private javax.swing.JPanel nomeBackground21;
    private javax.swing.JPanel nomeBackground22;
    private javax.swing.JPanel nomeBackground6;
    private javax.swing.JPanel nomeBackground7;
    private javax.swing.JPanel nomeBackground8;
    private javax.swing.JPanel nomeBackground9;
    private javax.swing.JTextField nomeTextField;
    // End of variables declaration//GEN-END:variables
}
