package telas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MASTER
 */
public class Pesquisa extends javax.swing.JFrame {

    /**
     * Creates new form Pesquisa
     */
    public Pesquisa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        backPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        nomeBackground = new javax.swing.JPanel();
        nomeTextField = new javax.swing.JTextField();
        dataField = new javax.swing.JLabel();
        nomeBackground7 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        dataField3 = new javax.swing.JLabel();
        nomeBackground8 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        dataField5 = new javax.swing.JLabel();
        nomeBackground14 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        dataField13 = new javax.swing.JLabel();
        dataField14 = new javax.swing.JLabel();
        dataField15 = new javax.swing.JLabel();
        nomeBackground16 = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        nomeBackground17 = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        nomeBackground18 = new javax.swing.JPanel();
        jTextField11 = new javax.swing.JTextField();
        dataField16 = new javax.swing.JLabel();
        nomeBackground19 = new javax.swing.JPanel();
        jTextField12 = new javax.swing.JTextField();
        dataField17 = new javax.swing.JLabel();
        nomeBackground20 = new javax.swing.JPanel();
        jTextField13 = new javax.swing.JTextField();
        dataField18 = new javax.swing.JLabel();
        dataField19 = new javax.swing.JLabel();
        nomeBackground23 = new javax.swing.JPanel();
        jTextField16 = new javax.swing.JTextField();
        dataField21 = new javax.swing.JLabel();
        nomeBackground22 = new javax.swing.JPanel();
        jTextField15 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        backPanel.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\MASTER\\Desktop\\Escola\\TP1\\TrabalhoFinal_Sindicato\\logoResized2.png")); // NOI18N

        nomeBackground.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackgroundLayout = new javax.swing.GroupLayout(nomeBackground);
        nomeBackground.setLayout(nomeBackgroundLayout);
        nomeBackgroundLayout.setHorizontalGroup(
            nomeBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nomeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );
        nomeBackgroundLayout.setVerticalGroup(
            nomeBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField.setText("Nome");

        nomeBackground7.setBackground(new java.awt.Color(53, 0, 113));

        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolher", "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viúvo(a)", "Separado(a) Judicialmente" }));

        javax.swing.GroupLayout nomeBackground7Layout = new javax.swing.GroupLayout(nomeBackground7);
        nomeBackground7.setLayout(nomeBackground7Layout);
        nomeBackground7Layout.setHorizontalGroup(
            nomeBackground7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1, 0, 104, Short.MAX_VALUE)
        );
        nomeBackground7Layout.setVerticalGroup(
            nomeBackground7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dataField3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField3.setText("Estado Civil");

        nomeBackground8.setBackground(new java.awt.Color(53, 0, 113));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nomeBackground8Layout = new javax.swing.GroupLayout(nomeBackground8);
        nomeBackground8.setLayout(nomeBackground8Layout);
        nomeBackground8Layout.setHorizontalGroup(
            nomeBackground8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );
        nomeBackground8Layout.setVerticalGroup(
            nomeBackground8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dataField5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField5.setText("Naturalidade-Nacionalidade");

        nomeBackground14.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackground14Layout = new javax.swing.GroupLayout(nomeBackground14);
        nomeBackground14.setLayout(nomeBackground14Layout);
        nomeBackground14Layout.setHorizontalGroup(
            nomeBackground14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        nomeBackground14Layout.setVerticalGroup(
            nomeBackground14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dataField13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField13.setText("Especialização");

        dataField14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField14.setText("Número CRO");

        dataField15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField15.setText("Universidade");

        nomeBackground16.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackground16Layout = new javax.swing.GroupLayout(nomeBackground16);
        nomeBackground16.setLayout(nomeBackground16Layout);
        nomeBackground16Layout.setHorizontalGroup(
            nomeBackground16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
        );
        nomeBackground16Layout.setVerticalGroup(
            nomeBackground16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground16Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        nomeBackground17.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackground17Layout = new javax.swing.GroupLayout(nomeBackground17);
        nomeBackground17.setLayout(nomeBackground17Layout);
        nomeBackground17Layout.setHorizontalGroup(
            nomeBackground17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField10)
        );
        nomeBackground17Layout.setVerticalGroup(
            nomeBackground17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground17Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        nomeBackground18.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackground18Layout = new javax.swing.GroupLayout(nomeBackground18);
        nomeBackground18.setLayout(nomeBackground18Layout);
        nomeBackground18Layout.setHorizontalGroup(
            nomeBackground18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
        );
        nomeBackground18Layout.setVerticalGroup(
            nomeBackground18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground18Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dataField16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField16.setText("Ano de Formatura");

        nomeBackground19.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackground19Layout = new javax.swing.GroupLayout(nomeBackground19);
        nomeBackground19.setLayout(nomeBackground19Layout);
        nomeBackground19Layout.setHorizontalGroup(
            nomeBackground19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
        );
        nomeBackground19Layout.setVerticalGroup(
            nomeBackground19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground19Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dataField17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField17.setText("Previsão de Graduação");

        nomeBackground20.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackground20Layout = new javax.swing.GroupLayout(nomeBackground20);
        nomeBackground20.setLayout(nomeBackground20Layout);
        nomeBackground20Layout.setHorizontalGroup(
            nomeBackground20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        nomeBackground20Layout.setVerticalGroup(
            nomeBackground20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground20Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dataField18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField18.setText("Semestres Cursados");

        dataField19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField19.setText("Endereço do Consultório");

        nomeBackground23.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackground23Layout = new javax.swing.GroupLayout(nomeBackground23);
        nomeBackground23.setLayout(nomeBackground23Layout);
        nomeBackground23Layout.setHorizontalGroup(
            nomeBackground23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField16)
        );
        nomeBackground23Layout.setVerticalGroup(
            nomeBackground23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground23Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dataField21.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dataField21.setText("Modalidade");

        nomeBackground22.setBackground(new java.awt.Color(53, 0, 113));

        javax.swing.GroupLayout nomeBackground22Layout = new javax.swing.GroupLayout(nomeBackground22);
        nomeBackground22.setLayout(nomeBackground22Layout);
        nomeBackground22Layout.setHorizontalGroup(
            nomeBackground22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField15, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );
        nomeBackground22Layout.setVerticalGroup(
            nomeBackground22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeBackground22Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout backPanelLayout = new javax.swing.GroupLayout(backPanel);
        backPanel.setLayout(backPanelLayout);
        backPanelLayout.setHorizontalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addComponent(logo)
                        .addGap(26, 26, 26)
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeBackground7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nomeBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(backPanelLayout.createSequentialGroup()
                                    .addComponent(dataField)
                                    .addGap(441, 441, 441)))
                            .addComponent(dataField3))
                        .addGap(249, 249, 249))
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backPanelLayout.createSequentialGroup()
                                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backPanelLayout.createSequentialGroup()
                                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(dataField14, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nomeBackground16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dataField16, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nomeBackground18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dataField19, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(146, 146, 146))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backPanelLayout.createSequentialGroup()
                                        .addComponent(nomeBackground20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeBackground19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dataField17)
                                    .addComponent(dataField18)
                                    .addComponent(nomeBackground22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(backPanelLayout.createSequentialGroup()
                                .addComponent(dataField5)
                                .addGap(113, 113, 113)
                                .addComponent(dataField13))
                            .addGroup(backPanelLayout.createSequentialGroup()
                                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(nomeBackground23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nomeBackground8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(dataField21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dataField15)
                                    .addComponent(nomeBackground14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nomeBackground17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        backPanelLayout.setVerticalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(backPanelLayout.createSequentialGroup()
                                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backPanelLayout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(dataField)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nomeBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)
                                        .addComponent(dataField3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nomeBackground7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(backPanelLayout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(logo)))
                                .addGap(38, 38, 38)
                                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dataField5)
                                    .addComponent(dataField13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeBackground8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nomeBackground14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataField21)
                            .addComponent(dataField15))
                        .addGap(1, 1, 1)
                        .addComponent(nomeBackground23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nomeBackground17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addComponent(dataField17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeBackground19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addComponent(dataField14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeBackground16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataField16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeBackground18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataField19)
                    .addComponent(dataField18))
                .addGap(4, 4, 4)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeBackground20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeBackground22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(347, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(backPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backPanel;
    private javax.swing.JLabel dataField;
    private javax.swing.JLabel dataField13;
    private javax.swing.JLabel dataField14;
    private javax.swing.JLabel dataField15;
    private javax.swing.JLabel dataField16;
    private javax.swing.JLabel dataField17;
    private javax.swing.JLabel dataField18;
    private javax.swing.JLabel dataField19;
    private javax.swing.JLabel dataField21;
    private javax.swing.JLabel dataField3;
    private javax.swing.JLabel dataField5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel nomeBackground;
    private javax.swing.JPanel nomeBackground14;
    private javax.swing.JPanel nomeBackground16;
    private javax.swing.JPanel nomeBackground17;
    private javax.swing.JPanel nomeBackground18;
    private javax.swing.JPanel nomeBackground19;
    private javax.swing.JPanel nomeBackground20;
    private javax.swing.JPanel nomeBackground22;
    private javax.swing.JPanel nomeBackground23;
    private javax.swing.JPanel nomeBackground7;
    private javax.swing.JPanel nomeBackground8;
    private javax.swing.JTextField nomeTextField;
    // End of variables declaration//GEN-END:variables
}
